2020-02-21 21:42:13,431 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.2
2020-02-21 21:42:13,432 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\program files\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2020-02-21-21-42-13-mpf-Gaming5.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2020-02-21 21:42:13,432 : INFO : Machine : MPF path: c:\program files\python36\lib\site-packages\mpf
2020-02-21 21:42:13,432 : INFO : Machine : Machine path: c:\MPF\Joust\monitor
2020-02-21 21:42:13,432 : INFO : Machine : Platform: win32
2020-02-21 21:42:13,432 : INFO : Machine : Python executable location: c:\program files\python36\python.exe
2020-02-21 21:42:13,432 : INFO : Machine : Python version: 3.6.4 (64-bit)
2020-02-21 21:42:13,432 : INFO : Machine : Machine config file #1: config.yaml
2020-02-21 21:42:13,433 : WARNING : ConfigProcessor : Cache file not found: C:\Users\Adrian\AppData\Local\Temp\3af4be3b6fd99989ee8008c873772a2a.mpf_cache
2020-02-21 21:42:13,433 : INFO : ConfigProcessor : Loading config from file c:\program files\python36\lib\site-packages\mpf\mpfconfig.yaml.
2020-02-21 21:42:13,508 : INFO : ConfigProcessor : Loading config: c:\program files\python36\lib\site-packages\mpf\mpfconfig.yaml
2020-02-21 21:42:13,870 : INFO : ConfigValidator : Config spec file cache created: C:\Users\Adrian\AppData\Local\Temp\config_spec.mpf_cache
2020-02-21 21:42:13,877 : INFO : ConfigProcessor : Loading config from file c:\MPF\Joust\monitor\config\config.yaml.
2020-02-21 21:42:13,878 : ERROR : root : Could not find file c:\MPF\Joust\monitor\config\config.yaml
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\mpf\core\file_manager.py", line 79, in load
    file = FileManager.locate_file(filename)
  File "c:\program files\python36\lib\site-packages\mpf\core\file_manager.py", line 53, in locate_file
    raise FileNotFoundError("File not found: {}".format(filename))
FileNotFoundError: File not found: c:\MPF\Joust\monitor\config\config.yaml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\mpf\commands\game.py", line 226, in __init__
    self.machine = MachineController(mpf_path, machine_path, vars(self.args))
  File "c:\program files\python36\lib\site-packages\mpf\core\machine.py", line 199, in __init__
    self._load_config()
  File "c:\program files\python36\lib\site-packages\mpf\core\machine.py", line 431, in _load_config
    store_to_cache=self.options['create_config_cache'])
  File "c:\program files\python36\lib\site-packages\mpf\core\config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\program files\python36\lib\site-packages\mpf\core\config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\program files\python36\lib\site-packages\mpf\core\file_manager.py", line 82, in load
    raise IOError("Could not find file {}".format(filename))
OSError: Could not find file c:\MPF\Joust\monitor\config\config.yaml
